// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "sso/internal/domain"

	dto "sso/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// TokenGenerator is an autogenerated mock type for the TokenGenerator type
type TokenGenerator struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: ctx, userDetails, appID
func (_m *TokenGenerator) GenerateToken(ctx context.Context, userDetails domain.UserDetails, appID string) (*dto.TokenGenerateResponse, error) {
	ret := _m.Called(ctx, userDetails, appID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 *dto.TokenGenerateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserDetails, string) (*dto.TokenGenerateResponse, error)); ok {
		return rf(ctx, userDetails, appID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserDetails, string) *dto.TokenGenerateResponse); ok {
		r0 = rf(ctx, userDetails, appID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.TokenGenerateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UserDetails, string) error); ok {
		r1 = rf(ctx, userDetails, appID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenGenerator creates a new instance of TokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGenerator {
	mock := &TokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
